// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQxJ7TJiRkUntParr2wV3qWXLwTPWrWSk',
    appId: '1:151596128119:web:6b824e102dbb160c763372',
    messagingSenderId: '151596128119',
    projectId: 'clueconn-73e93',
    authDomain: 'clueconn-73e93.firebaseapp.com',
    storageBucket: 'clueconn-73e93.appspot.com',
    measurementId: 'G-EVC0R7RD07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-X2xSInptb5zQ5Gz9bStp4u8Iy6oV6co',
    appId: '1:151596128119:android:9247d1883dec407f763372',
    messagingSenderId: '151596128119',
    projectId: 'clueconn-73e93',
    storageBucket: 'clueconn-73e93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsFoShgQNgjNRLmEIT_SPIZxHiWJvbWeo',
    appId: '1:151596128119:ios:ffc3c39298af7f34763372',
    messagingSenderId: '151596128119',
    projectId: 'clueconn-73e93',
    storageBucket: 'clueconn-73e93.appspot.com',
    androidClientId: '151596128119-gqpk47aj4gegl4jqikvgenhkeopa77g2.apps.googleusercontent.com',
    iosClientId: '151596128119-05m5deg367o7lfm0lqnlel0q1lvq6r8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsFoShgQNgjNRLmEIT_SPIZxHiWJvbWeo',
    appId: '1:151596128119:ios:ffc3c39298af7f34763372',
    messagingSenderId: '151596128119',
    projectId: 'clueconn-73e93',
    storageBucket: 'clueconn-73e93.appspot.com',
    androidClientId: '151596128119-gqpk47aj4gegl4jqikvgenhkeopa77g2.apps.googleusercontent.com',
    iosClientId: '151596128119-05m5deg367o7lfm0lqnlel0q1lvq6r8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );
}
